import { StyleSheet } from "react-native";

export const style = StyleSheet.create({
  container: {
    backgroundColor: "#c2e2f2",
    flex: 1,
  },
  boxBody: {
    flex: 10,
    paddingTop: 15,
  },
  textTitle: {
    paddingTop: 15,
    paddingHorizontal: 20,
    fontSize: 30,
    fontWeight: "700",
    color: "#49bce3",
  },
  boxBodyScrollView: {
    // paddingBottom: 20,
    paddingHorizontal: 20,
  },
  boxListTodo: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    marginTop: 10,
  },
  boxDetailTodo: {
    backgroundColor: "#fff",
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 5,
    marginBottom: 12,
    padding: 10,
    borderRadius: 7,
  },
  boxDetailTodoLeft: {
    width: "15%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  boxDetailTodoLeftTitle: {
    borderRadius: 7,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  boxColorLeft1: {
    backgroundColor: "#52f260",
  },
  boxColorLeft2: {
    backgroundColor: "#2fa9f5",
  },
  listTile: {
    fontSize: 15,
    fontWeight: "500",
    color: "#fff",
  },
  boxDetailTodoRight: {
    width: "85%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  boxDetailTodoRightTitle: {
    fontSize: 18,
    fontWeight: "500",
    color: "black",
  },
  boxBottom: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  boxBottomLeft: {
    width: "70%",
  },
  boxBottomLeftInput: {
    backgroundColor: "#fff",
    height: 40,
    borderRadius: 10,
    padding: 10,
    borderColor: "#7ddff5",
    borderWidth: 2,
  },
  boxBottomRight: {
    // width: "30%",
    // backgroundColor: "#2fa9f5",
    // borderColor: "#2fa9f5",
    // borderWidth: 1,
    // borderRadius: 10,
  },
  boxBottomRightButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 4,
    // elevation: 3,
    backgroundColor: "#2fa9f5",
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  titleModal: {
    fontSize: 16,
    fontWeight: "700",
    color: "black",
    textAlign: "center",
  },
  boxModal: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    gap: 30,
    marginTop: 10,
  },
  textBtnModal: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
});
